on: [push]

jobs:

  test_no_input:
    runs-on: ubuntu-latest
    name: no input
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/support-v2-upgrade
    - run: aws --version
      shell: bash


  test_latest_version_v1:
    runs-on: ubuntu-latest
    name: latest v1
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/support-v2-upgrade
      with:
        version: 1
    - run: aws --version
      shell: bash


  test_latest_version_v2:
    runs-on: ubuntu-latest
    name: latest v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/support-v2-upgrade
      with:
        version: 2
    - run: aws --version
      shell: bash


  test_specific_v1:
    runs-on: ubuntu-latest
    name: specific v1
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/support-v2-upgrade
      with:
        version: 1.18.1
    - run: aws --version
      shell: bash


  test_specific_v2:
    runs-on: ubuntu-latest
    name: specific v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/support-v2-upgrade
      with:
        version: 2.0.30
    - run: aws --version
      shell: bash
