name: test-action

on:
  push:
  workflow_dispatch:
    inputs:
      src_ref:
        description: Which branch to test?
        required: true
        default: feature/multiple-os

jobs:
  test_no_input:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: no input
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/multiple-os
    - run: aws --version
      shell: bash


  test_latest_version_v1:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: latest v1
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/multiple-os
      with:
        version: 1
    - run: aws --version
      shell: bash


  test_latest_version_v2:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: latest v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/multiple-os
      with:
        version: 2
        verbose: true
    - run: aws --version
      shell: bash


  test_specific_v1:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: specific v1
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/multiple-os
      with:
        version: 1.18.1
    - run: aws --version
      shell: bash


  test_specific_v2:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: specific v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@feature/multiple-os
      with:
        version: 2.0.30
    - run: aws --version
      shell: bash
