name: test-action

on:
  push:
  workflow_dispatch:
    inputs:
      src_repository:
        description: Source Repository - {owner}/{repo_name}
        required: true
      src_workflow_name:
        description: Source Workflow Name
        required: true
      src_sha:
        description: Source Repository SHA - GITHUB_SHA
        required: true

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "Specific v2"
            AWS_CLI_VERSION: "2.0.30"
          - TEST_NAME: "Latest v1"
            AWS_CLI_VERSION: "1"
          - TEST_NAME: "Specific v1"
            AWS_CLI_VERSION: "1.18.1"
          - TEST_NAME: "No Input"
          - TEST_NAME: "WORKDIR v1"
            WORKDIR: "/tmp/unfor19-awscli"
            AWS_CLI_VERSION: "1"
          - TEST_NAME: "WORKDIR v2"
            WORKDIR: "/tmp/unfor19-awscli"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "ROOTDIR v1"
            ROOTDIR: "/tmp"
            AWS_CLI_VERSION: "1"
          - TEST_NAME: "ROOTDIR v2"
            ROOTDIR: "/tmp"
            AWS_CLI_VERSION: "2"            
    name: Test ${{ matrix.TEST_NAME }} ${{ matrix.AWS_CLI_VERSION }}
    steps:
      - name: Test ${{ matrix.TEST_NAME }}
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: ${{ matrix.AWS_CLI_VERSION }}
          rootdir: ${{ matrix.ROOTDIR }}
          workdir: ${{ matrix.WORKDIR }}
      - run: aws --version
        shell: bash
    outputs:
      target_job_status: ${{ job.status }}

  update-status-check:
    name: Update Status Check In Source Repository
    runs-on: ubuntu-20.04
    needs:
      - test # Change if necessary
    if: ${{ always() }}
    steps:
      - name: Status Update Action Repo
        uses: unfor19/hero-action@master
        with:
          action: "status-update"
          gh_token: ${{ secrets.GH_TOKEN }} # scope: repo + workflow
          src_repository: ${{ github.event.inputs.src_repository }}
          src_workflow_name: ${{ github.event.inputs.src_workflow_name }}
          src_sha: ${{ github.event.inputs.src_sha }}
          target_repository: ${{ github.repository }}
          target_job_status: ${{ needs.test.outputs.target_job_status }}
          target_run_id: ${{ github.run_id }}
