name: test-action

on:
  push:
  workflow_dispatch:
    inputs:
      src_ref:
        description: Which branch to test?
        required: true
        default: master

jobs:
  test_no_input:
    runs-on: ubuntu-latest
    name: no input
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: chooban/install-aws-cli-action@d588bdde3d026638791d3ce99c0d5b63d3a08e9b
    - run: aws --version
      shell: bash


  test_latest_version_v1:
    runs-on: ubuntu-latest
    name: latest v1
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: chooban/install-aws-cli-action@d588bdde3d026638791d3ce99c0d5b63d3a08e9b
      with:
        version: 1
    - run: aws --version
      shell: bash


  test_latest_version_v2:
    runs-on: ubuntu-latest
    name: latest v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: chooban/install-aws-cli-action@d588bdde3d026638791d3ce99c0d5b63d3a08e9b
      with:
        version: 2
    - run: aws --version
      shell: bash


  test_specific_v1:
    runs-on: ubuntu-latest
    name: specific v1
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: chooban/install-aws-cli-action@d588bdde3d026638791d3ce99c0d5b63d3a08e9b
      with:
        version: 1.18.1
    - run: aws --version
      shell: bash


  test_specific_v2:
    runs-on: ubuntu-latest
    name: specific v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: chooban/install-aws-cli-action@d588bdde3d026638791d3ce99c0d5b63d3a08e9b
      with:
        version: 2.0.30
    - run: aws --version
      shell: bash


  test_lightsailctl_v2:
    runs-on: ubuntu-latest
    name: lightstailctl aws-cli-v2
    steps:
    - uses: actions/checkout@v2
    - id: install-aws-cli
      uses: chooban/install-aws-cli-action@d588bdde3d026638791d3ce99c0d5b63d3a08e9b
      with:
        version: 2.0.30
        lightsailctl: true
    - run: aws --version
      shell: bash